services:
  db:
    image: mysql:8.0
    platform: linux/arm64
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'your_strong_password' # MySQL root 비밀번호
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'your_password'             # 워드프레스 DB 유저 비밀번호

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    platform: linux/arm64
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'your_password'
      WORDPRESS_DB_NAME: 'wordpress'
    volumes:
      - ./lectus-class-system:/var/www/html/wp-content/plugins/lectus-class-system
      - ./lectus-academy-theme:/var/www/html/wp-content/themes/lectus-academy-theme
      - wordpress_data:/var/www/html

  wpcli:
    depends_on:
      - db
      - wordpress
    image: wordpress:cli
    platform: linux/arm64
    user: 33:33  # www-data user
    command: tail -f /dev/null
    volumes:
      - ./lectus-class-system:/var/www/html/wp-content/plugins/lectus-class-system
      - ./lectus-academy-theme:/var/www/html/wp-content/themes/lectus-academy-theme
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'your_password'
      WORDPRESS_DB_NAME: 'wordpress'

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  db_data:
  wordpress_data: