/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: [
    './*.php',
    './404.php',
    './archive.php',
    './search.php',
    './single-*.php',
    './template-parts/**/*.php',
    './inc/**/*.php',
    './js/**/*.js',
    './src/**/*.css',
  ],
  safelist: [
    'text-9xl',
    'text-3xl',
    'text-4xl',
    'md:text-4xl',
    'bg-blue-600',
    'hover:bg-blue-700',
    'bg-white',
    'hover:bg-blue-50',
    'border-blue-600',
    'text-blue-600',
    'px-6',
    'py-3',
    'w-32',
    'h-32',
    'w-20',
    'h-20',
    'w-30',
    'h-30',
    'shadow-2xl',
    'scale-105',
    'transition-all',
    'duration-300',
    'hover:shadow-xl',
    'sticky',
    'top-24',
    'aspect-video',
    'hover:scale-105',
    'transition-transform',
    'duration-300',
    'line-clamp-2',
    'col-span-full',
  ],
  theme: {
    extend: {
      colors: {
        'lectus-primary': '#2563eb',
        'lectus-secondary': '#7c3aed',
        'lectus-accent': '#f59e0b',
        'lectus-dark': '#1f2937',
        'lectus-light': '#f3f4f6',
      },
      fontFamily: {
        'sans': ['Pretendard', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
}

