/** @type {import('tailwindcss').Config} */
module.exports = {
  mode: 'jit',
  content: [
    './*.php',
    './404.php',
    './archive.php',
    './search.php',
    './single-*.php',
    './template-parts/**/*.php',
    './inc/**/*.php',
    './js/**/*.js',
    './src/**/*.css',
  ],
  future: {
    hoverOnlyWhenSupported: true,
  },
  safelist: [
    'text-9xl',
    'text-3xl',
    'text-4xl',
    'md:text-4xl',
    'bg-blue-600',
    'hover:bg-blue-700',
    'bg-white',
    'hover:bg-blue-50',
    'border-blue-600',
    'text-blue-600',
    'px-6',
    'py-3',
    'w-32',
    'h-32',
    'w-20',
    'h-20',
    'w-30',
    'h-30',
    'shadow-2xl',
    'scale-105',
    'transition-all',
    'duration-300',
    'hover:shadow-xl',
    'sticky',
    'top-24',
    'aspect-video',
    'hover:scale-105',
    'transition-transform',
    'duration-300',
    'line-clamp-2',
    'col-span-full',
    // Browser compatibility classes
    'ie-flex-fix',
    'grid-fallback',
    'course-layout',
    'course-content-wrapper',
    'course-main-content',
    'course-sidebar',
    'tab-navigation',
    'sticky-card',
    'js-fixed',
    // Enhanced Edge compatibility classes
    'course-grid',
    'course-card',
    'course-filters',
    'filter-group',
    'filter-select',
    'course-thumbnail',
    'course-content',
    'course-title',
    'course-categories',
    'category-tag',
    'course-excerpt',
    'course-meta',
    'meta-item',
    'course-footer',
    'course-price',
    'course-link',
    // Front page classes
    'hero-section',
    'hero-container',
    'hero-content',
    'hero-title',
    'hero-subtitle',
    'hero-search',
    'search-form',
    'search-input',
    'search-submit',
    'keywords-section',
    'keywords-container',
    'keywords-wrapper',
    'keywords-label',
    'keyword-tag',
    'featured-section',
    'featured-container',
    'featured-header',
    'featured-grid',
    'new-courses-section',
    'new-courses-container',
    'new-courses-header',
    'new-courses-grid',
    'categories-section',
    'categories-container',
    'categories-header',
    'categories-grid',
    'category-card',
    'category-content',
    'category-name',
    'category-count',
    'cta-section',
    'cta-container',
    'cta-title',
    'cta-subtitle',
    'cta-buttons',
    'cta-button-primary',
    'cta-button-secondary',
    'section-title',
    'view-all',
    'discount-badge',
    'new-badge',
    'course-instructor',
    'course-rating',
    'rating-stars',
    'rating-count',
    'course-pricing',
    'discount-percent',
    'original-price',
    'current-price',
  ],
  theme: {
    extend: {
      colors: {
        'lectus-primary': '#2563eb',
        'lectus-secondary': '#7c3aed',
        'lectus-accent': '#f59e0b',
        'lectus-dark': '#1f2937',
        'lectus-light': '#f3f4f6',
      },
      fontFamily: {
        'sans': ['Pretendard', 'ui-sans-serif', 'system-ui'],
      },
    },
  },
  plugins: [],
}

